/* eslint-disable @next/next/no-sync-scripts */

import '../styles/globals.css';
import { Inter } from 'next/font/google';
import { Navbar } from '@/components/navbar/Navbar';
import { Footer } from '@/components/footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cryptospace',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {

  return (
    <html lang="es">
      <head>
        <script>
          
        </script>

      </head>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        <script src='https://iframe.sandbox.test-simplexcc.com/form-sdk.js' type="text/javascript"></script>
        <script>
            window.simplex.createForm();
        </script>
      </body>
    </html>
  )
}
